from enum import Enum
class FinishReason(Enum):
  FINISH_REASON_UNSPECIFIED = 0
  NATURAL_STOP = 1
  MAX_TOKENS_REACHED = 2
  FLAGGED_SAFETY_REASON = 3
  FLAGGED_RECITATION_REASON = 4
  FLAGGED_UNKNOWN_REASON = 5